import type { Metadata } from 'next'
import '@/styles/globals.css'
import { orbitron } from './fonts'

export const metadata: Metadata = {
  title: 'Kitty AI',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Kitty AI',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Kitty AI',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={orbitron.className}>{children}</body>
    </html>
  )
}
