import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config/wallet'
import Web3ModalProvider from '@/contexts/wagmi'
import '@/styles/globals.css'
import { orbitron } from './fonts'

export const metadata: Metadata = {
  title: 'Kitty AI',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Kitty AI',
    type: 'website',
  },
  twitter: {
    card: 'summary',
    title: 'Kitty AI',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang='en'>
      <body className={orbitron.className}>
        <Web3ModalProvider initialState={initialState}>
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  )
}
